MODE: "Collect+Calib"
DATA_PATH: "/home/bionicdl-Mega/repos/flange_handeye_calibration/scripts/bionic_dl/data/"
ROBOT_CONTROLLER:
    ROBOT_TYPE: "Franka_ROS"
CIRCLE_FITTING:
    TYPE: "V2"
CALIBRATION:
    TYPE: "SVD"
    TARGET_DIR: "/home/bionicdl-Mega/repos/new/flange_handeye_calibration/flange_ground_truth/flange_franka.pcd"
    SOURCE_DIR: "/home/bionicdl-Mega/repos/new/flange_handeye_calibration/flange_ground_truth/flange_franka_ref.pcd"
PATH_GENERATOR:
    POINT_PATH: "/home/bionicdl-Mega/repos/flange_handeye_calibration/scripts/bionic_dl/configs/predef_pos_franka.txt"